### PR TITLE
Better command-line argument parsing

### PR DESCRIPTION
**Pull request by nealey**
I added argparse so I could call this for myself and my wife from cron, without needing two installs :)

### CODE REVIEW

**Comment by nealey** [comment]
Using the log ID was causing my events to be off by 6 hours (my timezone offset, currently). Since the Fitbit API doesn't mention anything about the log ID being a timestamp, I added code to do the calculation of time based on time zone entered by the user in the Fitbit account preferences.

**Comment by tantalor** [comment]
Please resolve merge conflicts

**Comment by nealey** [comment]
Are there any other changes you'd like made? I'm happy to keep merging into my fork, but I'd be happier if my changes were accepted upstream :)

**Comment by tantalor** [comment]
Looks good, I'll merge this. My only concern is there is now no default command so the `cron.sh` script will break; please add the "patch" command arg.

**Comment by nealey** [comment]
Okay, I modified `cron.sh` to invoke "patch", and also removed bash dependencies and what appear to be DOS batch file stylings :)

**Pull request merged**
